name: Build APK

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # - name: Build APK split per ABI
      #   run: flutter build apk --split-per-abi --release

      # - name: Upload APK (split per ABI)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-release-split-apk
      #     path: build/app/outputs/flutter-apk/
